Add "liens utiles" to student services
ClubInfoInsaT/application-amicale pull request #48
Opened 2022-07-28 08:40 UTC by Shinyhero36

## Issue
#32 

## Screenshot
![Screenshot_1658997493](https://user-images.githubusercontent.com/36128190/181461461-3a2ecf81-a577-4b0a-9cdb-939850587cff.png)

## Notes
- J'ai repris le même icône que celui pour WikiEtud (à voir s'il faut mettre autre chose si c'est redondant)

2022-07-30 08:54 UTC, Paulao17 requested changes
Good ! Works well, missing a few locales (translations) in places. Should at least have the French and English translation.

As commented, I propose copying the wiketud image for easier later modification.

2022-07-30 08:54 UTC, Paulao17 commented on src/utils/Services.ts
> +      title: 'Liens utiles',
Title should use `i18n`

2022-07-30 08:54 UTC, Paulao17 commented on src/utils/Services.ts
> +      image: Urls.images.wiketud,
I propose we copy the `Wiketud.png` image on `etud` to something like `LiensUtiles.png` (see [urls](/ClubInfoInsaT/application-amicale/blob/master/src/constants/Urls.tsx) ). That way we can later easily change the image without updating the app.

2022-07-30 15:41 UTC, Shinyhero36 commented
Theoretically, every items in services should use i18n in the title. That's why I let it in French.

2022-10-21 08:07 UTC, Paulao17 commented on src/utils/Services.ts
> +      image: Urls.images.wiketud,
Could you please use `https://etud.insa-toulouse.fr/~amicale_app/images/UsefulLinks.png` instead please ?

2022-11-21 15:25 UTC, Paulao17 commented
Resolves #32

2022-11-21 15:25 UTC, merged